name: Deploy Taller Data Lake

on:
  push:
    branches:
      - DEV
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/envs/dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # AWS Auth
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"

      # Solo en main se despliega
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="dev.tfvars"

      # Subir CSV a Bronze (solo en main)
      - name: Upload CSV extorsion
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp $GITHUB_WORKSPACE/terraform/archivos_para_bronze/extorsion.csv s3://datalake-bronze-444655873165/taller/

      # Subir scripts Glue (solo en main)
      - name: Upload Glue Script Great_Expectations
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp $GITHUB_WORKSPACE/terraform/archivos_para_bronze/scripts/great_expectation.py s3://aws-glue-assets-444655873165-us-east-1/scripts/Great_Expectations.py

      - name: Upload Glue Script bronze_to_silver
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp $GITHUB_WORKSPACE/terraform/archivos_para_bronze/scripts/bronze_to_silver.py s3://aws-glue-assets-444655873165-us-east-1/scripts/bronze_to_silver.py

      - name: Upload Glue Script silver_to_gold
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp $GITHUB_WORKSPACE/terraform/archivos_para_bronze/scripts/silver_to_gold.py s3://aws-glue-assets-444655873165-us-east-1/scripts/silver_to_gold.py